### ISSUE TITLE
Can't find config file

### ISSUE THREAD

**Issue by Madbeefer** [Eskander/haos-apps#103]
I've installed and uninstalled a few times and no luck in it creating a config file anywhere. I've gone ahead and made both the directories and files in the \addon_configs\2243a3f0_homer\config.yml
and \config\addon_configs\2243a3f0_homer\config.yml and still end up with the dummy page.

**Comment by Eskander** [comment]
What method are you using to access the config files (smb/ssh/other addons ...) ?

**Comment by Madbeefer** [comment]
I've used WinSCP and the embedded file editor in home assistant. And the home assistant FTP addon.

**Comment by Eskander** [comment]
Did you have access to `addon_configs/` directory using these methods?
Any other addons you have that correctly store configs under `addon_configs/`?
What's the version of Supervisor in your installation?

**Comment by Madbeefer** [comment]
I do have access to the folder. I have Tandoor that has a config file in there that works. 
Supervisor is 2025.03.3

**Comment by Eskander** [comment]
I pushed a new update (v1.17) that fixes some permission issues introduced by the upstream container.
Can you verify if the addon correctly creates config directory and files now under `/addon_configs/2243a3f0_homer` ?

**Comment by Madbeefer** [comment]
From what I can tell it didn't change it. I have a config file in there, but I still see the dummy page.

**Comment by Eskander** [comment]
I am unsure as to what the issue might be. Since the dummy page is generated, the addon should have proper access to its config folder, which is exposed by Supervisor.

Just to be sure, in _File editor_ addon, can you verify that you have _Enforce Basepath_ set to _False_ before accessing `/addon_configs/2243a3f0_homer` (not `/homeassistant/addon_configs...`) ?

Another troubleshooting step is to install _Terminal & SSH_ and run `ls -l /addon_configs` command. Post the output here.

**Comment by Madbeefer** [comment]
I hadn't been using file editor I'd been going in via FTP.. Which I guess was the wrong move, I changed that setting in file editor and I found it. Thanks for the help. I'm not sure why I didn't see it when I was in via FTP..

**Comment by Eskander** [comment]
Good to see the problem solved.
I don't use the FTP addon so I can't tell what went wrong.
